#!/bin/bash
set -x
SIZE=536870912 #1024*1024*512
export HSA_NO_SCRATCH_RECLAIM=1
LD_LIBRARY_PATH=./build/release/:$LD_LIBRARY_PATH \
TORCH_NCCL_USE_TENSOR_REGISTER_ALLOCATOR_HOOK=true \
NCCL_P2P_PCI_CHUNKSIZE=$SIZE NCCL_P2P_NVL_CHUNKSIZE=$SIZE NCCL_BUFFSIZE=$SIZE \
NCCL_P2P_NET_CHUNKSIZE=$SIZE \
	NCCL_PROTO="SIMPLE" NCCL_DEBUG=TRACE \
NCCL_P2P_USE_CUDA_MEMCPY=1 GPU_MAX_HW_QUEUES=8 NCCL_MAX_NCHANNELS=8 NCCL_MAX_P2P_NCHANNELS=8  python ./example.py
