LD_LIBRARY_PATH=./build/release/:$LD_LIBRARY_PATH \
NCCL_PROTO="SIMPLE" NCCL_DEBUG=TRACE \
NCCL_P2P_USE_CUDA_MEMCPY=1 GPU_MAX_HW_QUEUES=40 NCCL_MAX_NCHANNELS=8 NCCL_MAX_P2P_NCHANNELS=8  python ./example.py